### ISSUE TITLE
targetSdkVersion="26" Notifications not received on  some android device

### ISSUE THREAD

**Issue by eemi2010** [caffeinalab/ti.goosh#114]
If the app target targetSdkVersion="26". Notifications wont be displayed on Android devices below version 6. I think this is due to how application in the background should handle notifications.

**Comment by yuranevmer** [comment]
Same issue with receiving notifications in background on Android 8.
```
0-02 11:48:44.700  1969  3885 W ActivityManager: Background start not allowed: service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=ua.com.mhp.agro.dev cmp=ua.com.mhp.agro.dev/ti.goosh.IntentService (has extras) } to ua.com.mhp.agro.dev/ti.goosh.IntentService from pid=14856 uid=10165 pkg=ua.com.mhp.agro.dev
10-02 11:48:44.704 14856 14856 D AndroidRuntime: Shutting down VM
10-02 11:48:44.706  3263  3263 W GCM     : broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=ua.com.mhp.agro.dev (has extras) }
10-02 11:48:44.717 14856 14856 E AndroidRuntime: FATAL EXCEPTION: main
10-02 11:48:44.717 14856 14856 E AndroidRuntime: Process: ua.com.mhp.agro.dev, PID: 14856
10-02 11:48:44.717 14856 14856 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver ti.goosh.BroadcastReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=ua.com.mhp.agro.dev cmp=ua.com.mhp.agro.dev/ti.goosh.IntentService (has extras) }: app is in background uid UidRecord{9df5545 u0a165 RCVR bg:+1m2s763ms idle change:uncached procs:1 seq(0,0,0)}
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3228)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.app.ActivityThread.-wrap17(Unknown Source:0)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:171)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6633)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010 pkg=ua.com.mhp.agro.dev cmp=ua.com.mhp.agro.dev/ti.goosh.IntentService (has extras) }: app is in background uid UidRecord{9df5545 u0a165 RCVR bg:+1m2s763ms idle change:uncached procs:1 seq(0,0,0)}
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1531)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.app.ContextImpl.startService(ContextImpl.java:1487)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:660)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.content.ContextWrapper.startService(ContextWrapper.java:660)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at ti.goosh.BroadcastReceiver.onReceive(BroadcastReceiver.java:32)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3221)
10-02 11:48:44.717 14856 14856 E AndroidRuntime: 	... 8 more
```

**Comment by frodfigu** [comment]
Same problem here...
Any solution?

**Comment by DFoxinator** [comment]
Has anyone figured out a solution for this?

**Comment by furthurr** [comment]
I am using the appcelerator sdk 7.3.1.GA with the ti.goosh 4.1.1 and it's OK
but with the appcelertor sdk 7.4.X is failing

**Comment by DFoxinator** [comment]
I highly recommend using this plugin: https://github.com/hansemannn/titanium-firebase-cloud-messaging

It works perfectly and no crashes.

**Comment by andersdp** [comment]
Still no news on a fix for this?

Play Store now demands that updates has targetSdkVersion=26 so this is important.

**Comment by furthurr** [comment]
Good news .... there is a new push whit the fix 👍 
[Merge branch 'feature/oreo' ](https://github.com/caffeinalab/ti.goosh/commit/b7c8b4469cc0939beb0ded95bf8be7675f0fbeab)
I am whating for the dist version

**Comment by andersdp** [comment]
Let's hope that someone who make the a new release sees this (today) 🤞

**Comment by Jei** [comment]
We've merged that fix to try and make the module work with Android Oreo, but there are still things to do. As stated [in this comment](https://github.com/caffeinalab/ti.goosh/issues/109#issuecomment-407236974), there's been radical changes in the way Android handles services. You can find the details here: https://developer.android.com/about/versions/oreo/background.
Basically, methods like "GcmReceiver.startWakefulService()" will throw exception when they are called while the app is closed or flagged as "in background". This means that the current master of Ti.Goosh doesn't show notifications in those cases.
We're trying to migrate the module to the Firebase library to solve these issues.

**Comment by furthurr** [comment]
I have compiled the module ... 
[ti.goosh-android-4.1.1.zip](https://github.com/caffeinalab/ti.goosh/files/2556842/ti.goosh-android-4.1.1.zip)
I am testing android 8 and 7 (sdk 25,26) and i have problem with the custom sound on android 8 ... and  i have only this issue

**Comment by andersdp** [comment]
The good news: This fix solves getting push when app is backgrounded.

Bad news: The push does not show up when the app is dead. Furthermore our app stalls and eventually crashes when starting up from dead after having sent a push to the device.

**Comment by furthurr** [comment]
do you have ?
```
// subscribe

TiGoosh.subscribe({
	topic: "/topics/myTopic",
	success: function(e) {
		console.log("unsub done " + e);
	},
	error: function(e){
		console.error("error")
	}
})```

**Comment by eemi2010** [comment]
@furthurr  So we need to subscribe to a topic now ? Can be anything ?

**Comment by furthurr** [comment]
I think so, I had the same problem that @andersdp  says, so this way was solved xD.

**Comment by Jei** [comment]
@furthurr It seems unlikely that subscribing to a topic solves the problem of creating a background service from a backgrounded app.
Have you tried sending a notification to the app while it's closed? Is the notification displayed in the tray?

**Comment by furthurr** [comment]
this build have te last modification
[Uploading ti.goosh-android-4.1.1.zip…](ti.goosh)

**Comment by furthurr** [comment]
thiz is the las build example;
https://www.youtube.com/watch?v=4b8IyU3YbNU

**Comment by eemi2010** [comment]
@furthurr  will integrate  the build and keep you guyz updated. Thx :)

**Comment by yuranevmer** [comment]
Seems that build above doesn't have the latest changes. 
Works for me only after I built module manually from branch.
Tested when app is in background mode or closed (Android 8.0).

**Comment by Jei** [comment]
We've just released a new version of Ti.Goosh that should solve this problem. You can find it [here](https://github.com/caffeinalab/ti.goosh/releases/tag/v4.2.0).
Let us know if you're still experiencing the same problem with Ti.Goosh 4.2.0.

**Comment by Abdelalim-dev** [comment]
I tried the new version (4.2.0) and it worked just fine on Android 9.
