### ISSUE TITLE
NullPointer after recieving Push

### ISSUE THREAD

**Issue by inaffect-ag** [caffeinalab/ti.goosh#36]
Hi
When i send a push with firebase console, i get an nullpointer exception:
```
[INFO] :   I/ti.goosh.IntentService: Not showing notification cause missing data.alert
[ERROR] :  TiApplication: (AsyncTask #1) [15040,15040] Sending event: exception on thread: AsyncTask #1 msg:java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.gson.JsonObject.has(java.lang.String)' on a null object reference; Titanium 6.0.1,2016/12/19 16:51,undefined
[ERROR] :  TiApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.gson.JsonObject.has(java.lang.String)' on a null object reference
[ERROR] :  TiApplication: 	at ti.goosh.IntentService.parseNotification(IntentService.java:122)
[ERROR] :  TiApplication: 	at ti.goosh.IntentService.onMessageReceived(IntentService.java:54)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
[ERROR] :  TiApplication: 	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
[ERROR] :  TiApplication: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
[ERROR] :  TiApplication: 	at java.lang.Thread.run(Thread.java:761)
```
any idea how i could work it out?
In firebase console I tried using the basic message as well as the advanced options adding key/value but with same outcome.

I'm using v.2.0 of the module.

**Comment by progress44** [comment]
The firebase console doesn't send a `data` object which the module expects all the data to be in. I looked at the console a little but couldn't find a way to manipulate the payload therefore I don't think there's a way to make it work sending the notifications from the firebase console as of now

**Comment by inaffect-ag** [comment]
thanks!

**Comment by sapfear** [comment]
Hello, you can send from firebase console additional params in users data

key: data
field: {datacontentfield: "1"}
![screen shot 2017-04-22 at 11 27 45](https://cloud.githubusercontent.com/assets/22700763/25302079/bf42cce6-274e-11e7-851b-1d1a29ba5779.png)
