### ISSUE TITLE
NullpointerExceptions reported on Play Store

### ISSUE THREAD

**Issue by andersdp** [caffeinalab/ti.goosh#43]
We've gotten support tickets on crashes related to push notifications but the only one we've seen ourselves is on Android 4.x devices where the app is completely shut down and then crashes when opening an push notification. 

From the log on Play Store I get these two errors regarding goosh:

This one comes from Android 5.x - 7.x
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void ti.goosh.TiGooshModule.sendMessage(java.lang.String, java.lang.Boolean)' on a null object reference
	at ti.goosh.IntentService.parseNotification(IntentService.java:130)
	at ti.goosh.IntentService.onMessageReceived(IntentService.java:54)
	at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

This one comes from Android 4.4
```
java.lang.NullPointerException
	at ti.goosh.IntentService.parseNotification(IntentService.java:130)
	at ti.goosh.IntentService.onMessageReceived(IntentService.java:54)
	at com.google.android.gms.gcm.GcmListenerService.zzq(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzp(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zzo(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
	at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

Are these known bugs?

We're using ti.goosh 1.6.2 with Titanium SDK 5.5.1

**Comment by andersdp** [comment]
Glad to see this fixed. However we have not yet moved on to SDK 6.x

Is it possible to get a version compiled for SDK 5.5.1 with this fix. It would be really great!
